POST http://localhost:3001/task/rooms/765f6598-bf7e-4e4d-8b46-1d48960af4b9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZTZjZWY1YS1mZDkyLTQ5ZGMtYjVjNi0yMmQ5YjhjZmVkMjYiLCJlbWFpbCI6InNpY2tvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzcxNTAwNzc3LCJleHAiOjE3NzE2NzM1NzcsImF1ZCI6InRhc2tmbG93X3VzZXJzIiwiaXNzIjoidGFza2Zsb3dfYmFja2VuZCJ9.cnmpga798CEk5yG06nsaNjj9enBc3KcyA-QVQdQH-T4

{
    "title": "Lets sample this",
    "description": "Testintg the tasks endpoint",
    "dueDate": "2026-07-15T17:00:00Z"
}

PATCH http://localhost:3001/task/rooms/765f6598-bf7e-4e4d-8b46-1d48960af4b9/assign
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZTZjZWY1YS1mZDkyLTQ5ZGMtYjVjNi0yMmQ5YjhjZmVkMjYiLCJlbWFpbCI6InNpY2tvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzcxNTAwNzc3LCJleHAiOjE3NzE2NzM1NzcsImF1ZCI6InRhc2tmbG93X3VzZXJzIiwiaXNzIjoidGFza2Zsb3dfYmFja2VuZCJ9.cnmpga798CEk5yG06nsaNjj9enBc3KcyA-QVQdQH-T4

{
    "taskId": "d15fd754-dfd7-497c-be00-9102b42e905e",
    "assigneeId": "fa8267a3-707e-40ce-a932-437f7cae2d11"
}

GET http://localhost:3001/task/rooms/765f6598-bf7e-4e4d-8b46-1d48960af4b9
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZTZjZWY1YS1mZDkyLTQ5ZGMtYjVjNi0yMmQ5YjhjZmVkMjYiLCJlbWFpbCI6InNpY2tvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzcxNTAwNzc3LCJleHAiOjE3NzE2NzM1NzcsImF1ZCI6InRhc2tmbG93X3VzZXJzIiwiaXNzIjoidGFza2Zsb3dfYmFja2VuZCJ9.cnmpga798CEk5yG06nsaNjj9enBc3KcyA-QVQdQH-T4