DELETE http://localhost:3001/auth/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjZhYWUxZS05NGM1LTRlMzMtYTRjZC04NzY3ODQ2MTFjYzEiLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJpYXQiOjE3NzA3NTU0NDIsImV4cCI6MTc3MDkyODI0MiwiYXVkIjoidGFza2Zsb3dfdXNlcnMiLCJpc3MiOiJ0YXNrZmxvd19iYWNrZW5kIn0.W_V8qKqefJbBFbKpdP4kgeRyzOFQKxrC-q0iBhwcqag


{
    "email": "user@example.com",
    "password": "securepassword123"
}