POST http://localhost:3001/rooms
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZTZjZWY1YS1mZDkyLTQ5ZGMtYjVjNi0yMmQ5YjhjZmVkMjYiLCJlbWFpbCI6InNpY2tvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzcxNTAwMjg4LCJleHAiOjE3NzE2NzMwODgsImF1ZCI6InRhc2tmbG93X3VzZXJzIiwiaXNzIjoidGFza2Zsb3dfYmFja2VuZCJ9.RVnm9kDJBxRRYTflfZZSO6OfDZlEP4dXk7V7fkOTY08

{
  "name": "Sample Room"
  
  
}

GET http://localhost:3001/rooms/55d842be-189f-4936-8d34-e136665e8961
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZTZjZWY1YS1mZDkyLTQ5ZGMtYjVjNi0yMmQ5YjhjZmVkMjYiLCJlbWFpbCI6InNpY2tvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzcxNTAwMjg4LCJleHAiOjE3NzE2NzMwODgsImF1ZCI6InRhc2tmbG93X3VzZXJzIiwiaXNzIjoidGFza2Zsb3dfYmFja2VuZCJ9.RVnm9kDJBxRRYTflfZZSO6OfDZlEP4dXk7V7fkOTY08




POST http://localhost:3001/rooms/765f6598-bf7e-4e4d-8b46-1d48960af4b9/invite
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZTZjZWY1YS1mZDkyLTQ5ZGMtYjVjNi0yMmQ5YjhjZmVkMjYiLCJlbWFpbCI6InNpY2tvQGV4YW1wbGUuY29tIiwiaWF0IjoxNzcxNTAwMjg4LCJleHAiOjE3NzE2NzMwODgsImF1ZCI6InRhc2tmbG93X3VzZXJzIiwiaXNzIjoidGFza2Zsb3dfYmFja2VuZCJ9.RVnm9kDJBxRRYTflfZZSO6OfDZlEP4dXk7V7fkOTY08

{
  "email": "user@example.com"
}


POST http://localhost:3001/rooms/765f6598-bf7e-4e4d-8b46-1d48960af4b9/accept-invite
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYTgyNjdhMy03MDdlLTQwY2UtYTkzMi00MzdmN2NhZTJkMTEiLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJpYXQiOjE3NzE1MDA1MDcsImV4cCI6MTc3MTY3MzMwNywiYXVkIjoidGFza2Zsb3dfdXNlcnMiLCJpc3MiOiJ0YXNrZmxvd19iYWNrZW5kIn0.X6HxK6WnO_LZs23y8bbtNzY_1zmTzfpJvack9h-3rVo

{
    "inviteCode": "ANY2hG9W"
}

PATCH http://localhost:3001/rooms/55d842be-189f-4936-8d34-e136665e8961/transfer-ownership
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYTgyNjdhMy03MDdlLTQwY2UtYTkzMi00MzdmN2NhZTJkMTEiLCJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJpYXQiOjE3NzEzNjI3ODAsImV4cCI6MTc3MTUzNTU4MCwiYXVkIjoidGFza2Zsb3dfdXNlcnMiLCJpc3MiOiJ0YXNrZmxvd19iYWNrZW5kIn0.0L2SZ8qrnVW4ND56_Dnh_MYUJyjwRTq1KSTmXDIPW0o

{
    "newOwnerId": "f98567fc-8cd4-4d6b-9b53-82137083745f"
}